### PR TITLE
 ConvertFrom-EZLog : Handling of log messages with newline characters.

### PR DESCRIPTION
**Pull request by adzero**
Hi. 

I started using your module a few monthes ago and I find it as effective and useful as it is simple ! 
Nonetheless, I quickly encountered a problem when logging long text messages with exception details such as stacktrace. 
The command ConvertFrom-EZLog fails importing the content of a file when a least one log line contains a new line character.  
I forked the project and fixed the problem in the most simple but effective way. 

I hope you merge this in the next release. 

Kind regards,
Anthony

### CODE REVIEW

**Comment by adzero** [comment]
Hello @apetitjean . 

Any update about my PR ?

**Comment by adzero** [comment]
Hello @apetitjean , 

I give another try. Has this pull request a chance to be merged in a near future ?

Thanks

**Review by apetitjean — APPROVED** [review]

**Comment by apetitjean** [comment]
Approved!

**Comment by apetitjean** [comment]
Hello @adzero!

Sorry for the delay. I've juste approved your PR.

Thanks a lot!

Arnaud

**Pull request merged**
